name: EAS Build (Android - Development)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Step 5: Set Expo Token environment variable
      - name: Set EXPO_TOKEN
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Step 6: EAS Build for Android (Development)
      - name: EAS Build (Android - Development)
        run: |
          eas build --platform android --profile development --non-interactive | tee build_output.txt

      # Step 7: Capture the build link
      - name: Capture Build Link
        id: capture_link
        run: |
          BUILD_PAGE_URL=$(grep -o "https://expo.dev/accounts/.*/projects/.*/builds/.*" build_output.txt)
          echo "BUILD_PAGE_URL=${BUILD_PAGE_URL}" >> $GITHUB_ENV
          echo "BUILD_PAGE_URL=${BUILD_PAGE_URL}"

      # Step 8: Send message to Telegram with the captured link
      - name: Send message to Telegram
        if: success()
        run: |
          MESSAGE="Novidades! Temos uma nova versão de desenvolvimento!\nLink: $BUILD_PAGE_URL\nPara mais informações ou download acesse o link ou copie o link no seu expo para acesso ao preview."
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="${MESSAGE}" \
          -d parse_mode="Markdown"
