name: EAS Build (Android - Development)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Log in to Expo
        run: npx expo login --token ${{ secrets.EXPO_TOKEN }}

      - name: EAS Build (Android - Development)
        run: eas build --platform android --profile development --non-interactive
